
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Text.Json;
using GameFrameX.Core.Config;

namespace GameFrameX.Config.Tables
{
    public sealed partial class SoundsConfig : BeanBase
    {

        private System.Func<string, string, string> Translator;

        /*
        public SoundsConfig(int Id, string GroupName, string Path, string Title, string CharacterName) 
        {
            this.Id = Id;
            this.GroupName = GroupName;
            this.Path = Path;
            this.Title = Title;
            this.CharacterName = CharacterName;
            PostInit();
        }        
        */

        public SoundsConfig(JsonElement _buf) 
        {
            Translator = null;
            Id = _buf.GetProperty("id").GetInt32();
            GroupName = _buf.GetProperty("groupName").GetString();
            Path = _buf.GetProperty("path").GetString();
            Title = _buf.GetProperty("title").GetString();
            CharacterName = _buf.GetProperty("characterName").GetString();

            // Localization Key Begin
            Title_Localization_Key = Title;
            CharacterName_Localization_Key = CharacterName;
            // Localization Key End
        }
    
        public static SoundsConfig DeserializeSoundsConfig(JsonElement _buf)
        {
            return new Tables.SoundsConfig(_buf);
        }

        /// <summary>
        /// ID
        /// </summary>
        public int Id { private set; get; }
        /// <summary>
        /// 声音所属组
        /// </summary>
        public string GroupName { private set; get; }
        /// <summary>
        /// 声音所在的路径
        /// </summary>
        public string Path { private set; get; }
        /// <summary>
        /// 声音标题Key
        /// </summary>
        private string _Title;
        public string Title
        {
            get
            {
                if (Translator != null)
                {
                    return Translator(Title_Localization_Key, _Title);
                }
                return _Title;
            }
            private set => _Title = value;
        }
        /// <summary>
        /// 声音标题Key 的多语言Key
        /// </summary>
        public readonly string Title_Localization_Key;
        private string _CharacterName;
        public string CharacterName
        {
            get
            {
                if (Translator != null)
                {
                    return Translator(CharacterName_Localization_Key, _CharacterName);
                }
                return _CharacterName;
            }
            private set => _CharacterName = value;
        }
        public readonly string CharacterName_Localization_Key;

        private const int __ID__ = 4070031;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef(TablesComponent tables)
        {
            
            
            
            
            
        }

        public  void TranslateText(System.Func<string, string, string> translator)
        {
            Translator = translator;
        }

        public override string ToString()
        {
            return "{ "
            + "id:" + Id + ","
            + "groupName:" + GroupName + ","
            + "path:" + Path + ","
            + "title:" + Title + ","
            + "characterName:" + CharacterName + ","
            + "}";
        }

        partial void PostInit();
    }
}
