
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Text.Json;
using GameFrameX.Config.Core;

namespace GameFrameX.Config.ai
{
    public sealed partial class Blackboard : BeanBase
    {
        /*
        public Blackboard(string Name, string Desc, string ParentName, System.Collections.Generic.List<ai.BlackboardKey> Keys) 
        {
            this.Name = Name;
            this.Desc = Desc;
            this.ParentName = ParentName;
            this.ParentName_Ref = null;
            this.Keys = Keys;
            PostInit();
        }        
        */

        public Blackboard(JsonElement _buf) 
        {
            Name = _buf.GetProperty("name").GetString();
            Desc = _buf.GetProperty("desc").GetString();
            ParentName = _buf.GetProperty("parent_name").GetString();
            ParentName_Ref = null;
            { var __json0 = _buf.GetProperty("keys"); Keys = new System.Collections.Generic.List<ai.BlackboardKey>(__json0.GetArrayLength()); foreach(JsonElement __e0 in __json0.EnumerateArray()) { ai.BlackboardKey __v0;  __v0 = ai.BlackboardKey.DeserializeBlackboardKey(__e0);  Keys.Add(__v0); }   }
        }
    
        public static Blackboard DeserializeBlackboard(JsonElement _buf)
        {
            return new ai.Blackboard(_buf);
        }

        public string Name { private set; get; }
        public string Desc { private set; get; }
        public string ParentName { private set; get; }
        public ai.Blackboard ParentName_Ref { private set; get; }
        public System.Collections.Generic.List<ai.BlackboardKey> Keys { private set; get; }

        private const int __ID__ = 1576193005;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef(TablesComponent tables)
        {
            
            
            ParentName_Ref = tables.TbBlackboard.Get(ParentName);
            foreach (var _e in Keys) { _e?.ResolveRef(tables); }
        }

        public override string ToString()
        {
            return "{ "
            + "name:" + Name + ","
            + "desc:" + Desc + ","
            + "parentName:" + ParentName + ","
            + "keys:" + StringUtil.CollectionToString(Keys) + ","
            + "}";
        }

        partial void PostInit();
    }
}
