
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Text.Json;
using GameFrameX.Config.Core;

namespace GameFrameX.Config.ai
{
    public sealed partial class ChooseTarget : ai.Service
    {
        /*
        public ChooseTarget(int Id, string NodeName, string ResultTargetKey)  : base(Id, NodeName) 
        {
            this.ResultTargetKey = ResultTargetKey;
            PostInit();
        }        
        */

        public ChooseTarget(JsonElement _buf)  : base(_buf) 
        {
            ResultTargetKey = _buf.GetProperty("result_target_key").GetString();
        }
    
        public static ChooseTarget DeserializeChooseTarget(JsonElement _buf)
        {
            return new ai.ChooseTarget(_buf);
        }

        public string ResultTargetKey { private set; get; }

        private const int __ID__ = 1601247918;
        public override int GetTypeId() => __ID__;

        public override void ResolveRef(TablesComponent tables)
        {
            base.ResolveRef(tables);
            
        }

        public override string ToString()
        {
            return "{ "
            + "id:" + Id + ","
            + "nodeName:" + NodeName + ","
            + "resultTargetKey:" + ResultTargetKey + ","
            + "}";
        }

        partial void PostInit();
    }
}
