
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Text.Json;
using GameFrameX.Config.Core;

namespace GameFrameX.Config.ai
{
    public sealed partial class ChooseSkill : ai.Task
    {
        /*
        public ChooseSkill(int Id, string NodeName, System.Collections.Generic.List<ai.Decorator> Decorators, System.Collections.Generic.List<ai.Service> Services, bool IgnoreRestartSelf, string TargetActorKey, string ResultSkillIdKey)  : base(Id, NodeName, Decorators, Services, IgnoreRestartSelf) 
        {
            this.TargetActorKey = TargetActorKey;
            this.ResultSkillIdKey = ResultSkillIdKey;
            PostInit();
        }        
        */

        public ChooseSkill(JsonElement _buf)  : base(_buf) 
        {
            TargetActorKey = _buf.GetProperty("target_actor_key").GetString();
            ResultSkillIdKey = _buf.GetProperty("result_skill_id_key").GetString();
        }
    
        public static ChooseSkill DeserializeChooseSkill(JsonElement _buf)
        {
            return new ai.ChooseSkill(_buf);
        }

        public string TargetActorKey { private set; get; }
        public string ResultSkillIdKey { private set; get; }

        private const int __ID__ = -918812268;
        public override int GetTypeId() => __ID__;

        public override void ResolveRef(TablesComponent tables)
        {
            base.ResolveRef(tables);
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "id:" + Id + ","
            + "nodeName:" + NodeName + ","
            + "decorators:" + StringUtil.CollectionToString(Decorators) + ","
            + "services:" + StringUtil.CollectionToString(Services) + ","
            + "ignoreRestartSelf:" + IgnoreRestartSelf + ","
            + "targetActorKey:" + TargetActorKey + ","
            + "resultSkillIdKey:" + ResultSkillIdKey + ","
            + "}";
        }

        partial void PostInit();
    }
}
