
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Text.Json;
using GameFrameX.Config.Core;

namespace GameFrameX.Config.ai
{
    public sealed partial class DebugPrint : ai.Task
    {
        /*
        public DebugPrint(int Id, string NodeName, System.Collections.Generic.List<ai.Decorator> Decorators, System.Collections.Generic.List<ai.Service> Services, bool IgnoreRestartSelf, string Text)  : base(Id, NodeName, Decorators, Services, IgnoreRestartSelf) 
        {
            this.Text = Text;
            PostInit();
        }        
        */

        public DebugPrint(JsonElement _buf)  : base(_buf) 
        {
            Text = _buf.GetProperty("text").GetString();
        }
    
        public static DebugPrint DeserializeDebugPrint(JsonElement _buf)
        {
            return new ai.DebugPrint(_buf);
        }

        public string Text { private set; get; }

        private const int __ID__ = 1357409728;
        public override int GetTypeId() => __ID__;

        public override void ResolveRef(TablesComponent tables)
        {
            base.ResolveRef(tables);
            
        }

        public override string ToString()
        {
            return "{ "
            + "id:" + Id + ","
            + "nodeName:" + NodeName + ","
            + "decorators:" + StringUtil.CollectionToString(Decorators) + ","
            + "services:" + StringUtil.CollectionToString(Services) + ","
            + "ignoreRestartSelf:" + IgnoreRestartSelf + ","
            + "text:" + Text + ","
            + "}";
        }

        partial void PostInit();
    }
}
