
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Text.Json;
using GameFrameX.Config.Core;

namespace GameFrameX.Config.ai
{
    public sealed partial class ExecuteTimeStatistic : ai.Service
    {
        /*
        public ExecuteTimeStatistic(int Id, string NodeName)  : base(Id, NodeName) 
        {
            PostInit();
        }        
        */

        public ExecuteTimeStatistic(JsonElement _buf)  : base(_buf) 
        {
        }
    
        public static ExecuteTimeStatistic DeserializeExecuteTimeStatistic(JsonElement _buf)
        {
            return new ai.ExecuteTimeStatistic(_buf);
        }


        private const int __ID__ = 990693812;
        public override int GetTypeId() => __ID__;

        public override void ResolveRef(TablesComponent tables)
        {
            base.ResolveRef(tables);
        }

        public override string ToString()
        {
            return "{ "
            + "id:" + Id + ","
            + "nodeName:" + NodeName + ","
            + "}";
        }

        partial void PostInit();
    }
}
