
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Text.Json;
using GameFrameX.Core.Config;

namespace GameFrameX.Config.ai
{
    public sealed partial class IsNotSet : ai.KeyQueryOperator
    {
        /*
        public IsNotSet()  : base() 
        {
            PostInit();
        }        
        */

        public IsNotSet(JsonElement _buf)  : base(_buf) 
        {
        }
    
        public static IsNotSet DeserializeIsNotSet(JsonElement _buf)
        {
            return new ai.IsNotSet(_buf);
        }


        private const int __ID__ = 790736255;
        public override int GetTypeId() => __ID__;

        public override void ResolveRef(TablesComponent tables)
        {
            base.ResolveRef(tables);
        }

        public override string ToString()
        {
            return "{ "
            + "}";
        }

        partial void PostInit();
    }
}
