
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Text.Json;
using GameFrameX.Config.Core;

namespace GameFrameX.Config.ai
{
    public sealed partial class IsSet2 : ai.KeyQueryOperator
    {
        /*
        public IsSet2()  : base() 
        {
            PostInit();
        }        
        */

        public IsSet2(JsonElement _buf)  : base(_buf) 
        {
        }
    
        public static IsSet2 DeserializeIsSet2(JsonElement _buf)
        {
            return new ai.IsSet2(_buf);
        }


        private const int __ID__ = -843729664;
        public override int GetTypeId() => __ID__;

        public override void ResolveRef(TablesComponent tables)
        {
            base.ResolveRef(tables);
        }

        public override string ToString()
        {
            return "{ "
            + "}";
        }

        partial void PostInit();
    }
}
