
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Text.Json;
using GameFrameX.Core.Config;

namespace GameFrameX.Config.ai
{
    public sealed partial class KeepFaceTarget : ai.Service
    {
        /*
        public KeepFaceTarget(int Id, string NodeName, string TargetActorKey)  : base(Id, NodeName) 
        {
            this.TargetActorKey = TargetActorKey;
            PostInit();
        }        
        */

        public KeepFaceTarget(JsonElement _buf)  : base(_buf) 
        {
            TargetActorKey = _buf.GetProperty("target_actor_key").GetString();
        }
    
        public static KeepFaceTarget DeserializeKeepFaceTarget(JsonElement _buf)
        {
            return new ai.KeepFaceTarget(_buf);
        }

        public string TargetActorKey { private set; get; }

        private const int __ID__ = 1195270745;
        public override int GetTypeId() => __ID__;

        public override void ResolveRef(TablesComponent tables)
        {
            base.ResolveRef(tables);
            
        }

        public override string ToString()
        {
            return "{ "
            + "id:" + Id + ","
            + "nodeName:" + NodeName + ","
            + "targetActorKey:" + TargetActorKey + ","
            + "}";
        }

        partial void PostInit();
    }
}
