
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Text.Json;
using GameFrameX.Config.Core;

namespace GameFrameX.Config.ai
{
    public partial class TbBlackboard : BaseDataTable<ai.Blackboard>
    {
        //private readonly System.Collections.Generic.Dictionary<string, ai.Blackboard> _dataMap;
        //private readonly System.Collections.Generic.List<ai.Blackboard> _dataList;
    
        //public System.Collections.Generic.Dictionary<string, ai.Blackboard> DataMap => _dataMap;
        //public System.Collections.Generic.List<ai.Blackboard> DataList => _dataList;
        //public ai.Blackboard GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
        //public ai.Blackboard Get(string key) => _dataMap[key];
        //public ai.Blackboard this[string key] => _dataMap[key];
    
        public override async System.Threading.Tasks.Task LoadAsync()
        {
            var jsonElement = await _loadFunc();
            DataList.Clear();
            LongDataMaps.Clear();
            StringDataMaps.Clear();
            foreach(var element in jsonElement.EnumerateArray())
            {
                ai.Blackboard _v;
                _v = ai.Blackboard.DeserializeBlackboard(element);
                DataList.Add(_v);
                StringDataMaps.Add(_v.Name.ToString(), _v);
            }
            PostInit();
        }

        public void ResolveRef(TablesComponent tables)
        {
            foreach(var element in DataList)
            {
                element.ResolveRef(tables);
            }
        }
    
    
        partial void PostInit();

        public TbBlackboard(Func<Task<JsonElement>> loadFunc) : base(loadFunc)
        {
        }
    }
}
