
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Text.Json;
using GameFrameX.Config.Core;

namespace GameFrameX.Config.ai
{
    public sealed partial class UeWaitBlackboardTime : ai.Task
    {
        /*
        public UeWaitBlackboardTime(int Id, string NodeName, System.Collections.Generic.List<ai.Decorator> Decorators, System.Collections.Generic.List<ai.Service> Services, bool IgnoreRestartSelf, string BlackboardKey)  : base(Id, NodeName, Decorators, Services, IgnoreRestartSelf) 
        {
            this.BlackboardKey = BlackboardKey;
            PostInit();
        }        
        */

        public UeWaitBlackboardTime(JsonElement _buf)  : base(_buf) 
        {
            BlackboardKey = _buf.GetProperty("blackboard_key").GetString();
        }
    
        public static UeWaitBlackboardTime DeserializeUeWaitBlackboardTime(JsonElement _buf)
        {
            return new ai.UeWaitBlackboardTime(_buf);
        }

        public string BlackboardKey { private set; get; }

        private const int __ID__ = 1215378271;
        public override int GetTypeId() => __ID__;

        public override void ResolveRef(TablesComponent tables)
        {
            base.ResolveRef(tables);
            
        }

        public override string ToString()
        {
            return "{ "
            + "id:" + Id + ","
            + "nodeName:" + NodeName + ","
            + "decorators:" + StringUtil.CollectionToString(Decorators) + ","
            + "services:" + StringUtil.CollectionToString(Services) + ","
            + "ignoreRestartSelf:" + IgnoreRestartSelf + ","
            + "blackboardKey:" + BlackboardKey + ","
            + "}";
        }

        partial void PostInit();
    }
}
