
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Text.Json;
using GameFrameX.Core.Config;

namespace GameFrameX.Config.l10n
{
    public partial class TbL10NDemo : BaseDataTable<l10n.L10NDemo>
    {
        //private readonly System.Collections.Generic.Dictionary<int, l10n.L10NDemo> _dataMap;
        //private readonly System.Collections.Generic.List<l10n.L10NDemo> _dataList;
    
        //public System.Collections.Generic.Dictionary<int, l10n.L10NDemo> DataMap => _dataMap;
        //public System.Collections.Generic.List<l10n.L10NDemo> DataList => _dataList;
        //public l10n.L10NDemo GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
        //public l10n.L10NDemo Get(int key) => _dataMap[key];
        //public l10n.L10NDemo this[int key] => _dataMap[key];
    
        public override async System.Threading.Tasks.Task LoadAsync()
        {
            var jsonElement = await _loadFunc();
            DataList.Clear();
            LongDataMaps.Clear();
            StringDataMaps.Clear();
            foreach(var element in jsonElement.EnumerateArray())
            {
                l10n.L10NDemo _v;
                _v = l10n.L10NDemo.DeserializeL10NDemo(element);
                DataList.Add(_v);
                LongDataMaps.Add(_v.Id, _v);
                StringDataMaps.Add(_v.Id.ToString(), _v);
            }
            PostInit();
        }

        public void ResolveRef(TablesComponent tables)
        {
            foreach(var element in DataList)
            {
                element.ResolveRef(tables);
            }
        }
    
    
        partial void PostInit();

        public TbL10NDemo(Func<Task<JsonElement>> loadFunc) : base(loadFunc)
        {
        }
    }
}
