
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Text.Json;
using GameFrameX.Core.Config;

namespace GameFrameX.Config
{
    public sealed partial class LLKLayout : BeanBase
    {
        /*
        public LLKLayout(int Col, int Row) 
        {
            this.Col = Col;
            this.Row = Row;
            PostInit();
        }        
        */

        public LLKLayout(JsonElement _buf) 
        {
            Col = _buf.GetProperty("col").GetInt32();
            Row = _buf.GetProperty("row").GetInt32();
        }
    
        public static LLKLayout DeserializeLLKLayout(JsonElement _buf)
        {
            return new LLKLayout(_buf);
        }

        /// <summary>
        /// 列
        /// </summary>
        public int Col { private set; get; }
        /// <summary>
        /// 行
        /// </summary>
        public int Row { private set; get; }

        private const int __ID__ = -505574955;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef(TablesComponent tables)
        {
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "col:" + Col + ","
            + "row:" + Row + ","
            + "}";
        }

        partial void PostInit();
    }
}
