
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Text.Json;
using GameFrameX.Core.Config;

namespace GameFrameX.Config
{
    /// <summary>
    /// 用于资源在游戏内的名字展示,以及资源在目录下的资产名称
    /// </summary>
    public sealed partial class ResourceCKBean : BeanBase
    {
        /*
        public ResourceCKBean(string Content, string FileName) 
        {
            this.Content = Content;
            this.FileName = FileName;
            PostInit();
        }        
        */

        public ResourceCKBean(JsonElement _buf) 
        {
            Content = _buf.GetProperty("content").GetString();
            FileName = _buf.GetProperty("file_name").GetString();
        }
    
        public static ResourceCKBean DeserializeResourceCKBean(JsonElement _buf)
        {
            return new ResourceCKBean(_buf);
        }

        /// <summary>
        /// 名字
        /// </summary>
        public string Content { private set; get; }
        /// <summary>
        /// 对应资源的文件名
        /// </summary>
        public string FileName { private set; get; }

        private const int __ID__ = -1539577370;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef(TablesComponent tables)
        {
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "content:" + Content + ","
            + "fileName:" + FileName + ","
            + "}";
        }

        partial void PostInit();
    }
}
