
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Text.Json;
using GameFrameX.Core.Config;

namespace GameFrameX.Config
{
    /// <summary>
    /// 用于设置多立绘的位置和资源获取
    /// </summary>
    public sealed partial class ShowPositionAndResId : BeanBase
    {
        /*
        public ShowPositionAndResId(res.ShowPostion PaintingPostion, string ResId) 
        {
            this.PaintingPostion = PaintingPostion;
            this.ResId = ResId;
            PostInit();
        }        
        */

        public ShowPositionAndResId(JsonElement _buf) 
        {
            PaintingPostion = (res.ShowPostion)_buf.GetProperty("painting_postion").GetInt32();
            ResId = _buf.GetProperty("res_id").GetString();
        }
    
        public static ShowPositionAndResId DeserializeShowPositionAndResId(JsonElement _buf)
        {
            return new ShowPositionAndResId(_buf);
        }

        /// <summary>
        /// 立绘位置
        /// </summary>
        public res.ShowPostion PaintingPostion { private set; get; }
        /// <summary>
        /// 资源ID
        /// </summary>
        public string ResId { private set; get; }

        private const int __ID__ = 419216330;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef(TablesComponent tables)
        {
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "paintingPostion:" + PaintingPostion + ","
            + "resId:" + ResId + ","
            + "}";
        }

        partial void PostInit();
    }
}
