
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Text.Json;
using GameFrameX.Core.Config;

namespace GameFrameX.Config
{
    /// <summary>
    /// 用于设置剧情的前置条件配置
    /// </summary>
    public sealed partial class StoryCondition : BeanBase
    {
        /*
        public StoryCondition(int StoryId, story.ConditionType Type, System.Collections.Generic.List<int> Condition) 
        {
            this.StoryId = StoryId;
            this.Type = Type;
            this.Condition = Condition;
            PostInit();
        }        
        */

        public StoryCondition(JsonElement _buf) 
        {
            StoryId = _buf.GetProperty("StoryId").GetInt32();
            Type = (story.ConditionType)_buf.GetProperty("Type").GetInt32();
            { var __json0 = _buf.GetProperty("Condition"); Condition = new System.Collections.Generic.List<int>(__json0.GetArrayLength()); foreach(JsonElement __e0 in __json0.EnumerateArray()) { int __v0;  __v0 = __e0.GetInt32();  Condition.Add(__v0); }   }
        }
    
        public static StoryCondition DeserializeStoryCondition(JsonElement _buf)
        {
            return new StoryCondition(_buf);
        }

        /// <summary>
        /// 剧情ID
        /// </summary>
        public int StoryId { private set; get; }
        /// <summary>
        /// 类型
        /// </summary>
        public story.ConditionType Type { private set; get; }
        /// <summary>
        /// 条件
        /// </summary>
        public System.Collections.Generic.List<int> Condition { private set; get; }

        private const int __ID__ = -1393056826;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef(TablesComponent tables)
        {
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "StoryId:" + StoryId + ","
            + "Type:" + Type + ","
            + "Condition:" + StringUtil.CollectionToString(Condition) + ","
            + "}";
        }

        partial void PostInit();
    }
}
