
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Text.Json;
using GameFrameX.Core.Config;
using GameFrameX.Config;

namespace GameFrameX.Config
{
    public partial class TablesComponent
    {
        internal item.TbAchievement TbAchievement { private set; get; }
        internal item.TbSounds TbSounds { private set; get; }
    
        private ConfigComponent m_ConfigComponent;

        public void Init(ConfigComponent configComponent)
        {
            m_ConfigComponent = configComponent;
            configComponent.RemoveAllConfigs();
        }

        public async System.Threading.Tasks.Task LoadAsync(System.Func<string, System.Threading.Tasks.Task<JsonElement>> loader)
        {
            //m_ConfigComponent.RemoveAllConfigs();
            var loadTasks = new System.Collections.Generic.List<System.Threading.Tasks.Task>();
    
            TbAchievement = new item.TbAchievement(() => loader("item_tbachievement"));
            loadTasks.Add(TbAchievement.LoadAsync());
            m_ConfigComponent.Add(nameof(item.TbAchievement), TbAchievement);

            TbSounds = new item.TbSounds(() => loader("item_tbsounds"));
            loadTasks.Add(TbSounds.LoadAsync());
            m_ConfigComponent.Add(nameof(item.TbSounds), TbSounds);

    
            await System.Threading.Tasks.Task.WhenAll(loadTasks);
    
            Refresh();
        }

        public TablesComponent()
        {
            //TablesMemory.BeginRecord();
    
            // TbAchievement = new item.TbAchievement();
            // TbSounds = new item.TbSounds();
            //TablesMemory.EndRecord();
        }

        public void Refresh()
        {
            PostInit();
            ResolveRef();
        }

        private void ResolveRef()
        {
            TbAchievement.ResolveRef(this);
            TbSounds.ResolveRef(this);
        }
    
        partial void PostInit();
    }
}
