
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Text.Json;
using GameFrameX.Core.Config;

namespace GameFrameX.Config.test
{
    public partial class TbSingleton : BaseDataTable<test.DemoSingletonType>
    {
    
        private test.DemoSingletonType _data;
        public test.DemoSingletonType Data => _data;

        public int Id => _data.Id;
        public string Name => _data.Name;
        public test.DemoDynamic Date => _data.Date;
    
        public override async Task LoadAsync()
        {
            var jsonElement = await _loadFunc();

            int n = jsonElement.GetArrayLength();
            if (n != 1) throw new SerializationException("table mode=one, but size != 1");
            _data = test.DemoSingletonType.DeserializeDemoSingletonType(jsonElement[0]);
        }

        public void ResolveRef(TablesComponent tables)
        {
            _data.ResolveRef(tables);
        }
    
        partial void PostInit();

        public TbSingleton(Func<Task<JsonElement>> loadFunc) : base(loadFunc)
        {
        }
    }
}
