
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Text.Json;
using GameFrameX.Core.Config;

namespace GameFrameX.Config.test
{
    public sealed partial class TestBeRef : BeanBase
    {
        /*
        public TestBeRef(int Id, int Count) 
        {
            this.Id = Id;
            this.Count = Count;
            PostInit();
        }        
        */

        public TestBeRef(JsonElement _buf) 
        {
            Id = _buf.GetProperty("id").GetInt32();
            Count = _buf.GetProperty("count").GetInt32();
        }
    
        public static TestBeRef DeserializeTestBeRef(JsonElement _buf)
        {
            return new test.TestBeRef(_buf);
        }

        public int Id { private set; get; }
        public int Count { private set; get; }

        private const int __ID__ = 1934403938;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef(TablesComponent tables)
        {
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "id:" + Id + ","
            + "count:" + Count + ","
            + "}";
        }

        partial void PostInit();
    }
}
