
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Text.Json;
using GameFrameX.Core.Config;

namespace GameFrameX.Config.test
{
    public sealed partial class InnerGroup : BeanBase
    {
        /*
        public InnerGroup(int Y1, int Y3, int Y4) 
        {
            this.Y1 = Y1;
            this.Y3 = Y3;
            this.Y4 = Y4;
            PostInit();
        }        
        */

        public InnerGroup(JsonElement _buf) 
        {
            Y1 = _buf.GetProperty("y1").GetInt32();
            Y3 = _buf.GetProperty("y3").GetInt32();
            Y4 = _buf.GetProperty("y4").GetInt32();
        }
    
        public static InnerGroup DeserializeInnerGroup(JsonElement _buf)
        {
            return new test.InnerGroup(_buf);
        }

        public int Y1 { private set; get; }
        public int Y3 { private set; get; }
        public int Y4 { private set; get; }

        private const int __ID__ = -587873083;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef(TablesComponent tables)
        {
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "y1:" + Y1 + ","
            + "y3:" + Y3 + ","
            + "y4:" + Y4 + ","
            + "}";
        }

        partial void PostInit();
    }
}
