
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Text.Json;
using GameFrameX.Core.Config;

namespace GameFrameX.Config.test
{
    public sealed partial class Path : BeanBase
    {
        /*
        public Path(int Id, string Res) 
        {
            this.Id = Id;
            this.Res = Res;
            PostInit();
        }        
        */

        public Path(JsonElement _buf) 
        {
            Id = _buf.GetProperty("id").GetInt32();
            Res = _buf.GetProperty("res").GetString();
        }
    
        public static Path DeserializePath(JsonElement _buf)
        {
            return new test.Path(_buf);
        }

        public int Id { private set; get; }
        public string Res { private set; get; }

        private const int __ID__ = -1226450911;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef(TablesComponent tables)
        {
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "id:" + Id + ","
            + "res:" + Res + ","
            + "}";
        }

        partial void PostInit();
    }
}
