
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Text.Json;
using GameFrameX.Core.Config;

namespace GameFrameX.Config.test
{
    public sealed partial class NotIndexList : BeanBase
    {
        /*
        public NotIndexList(int X, int Y) 
        {
            this.X = X;
            this.Y = Y;
            PostInit();
        }        
        */

        public NotIndexList(JsonElement _buf) 
        {
            X = _buf.GetProperty("x").GetInt32();
            Y = _buf.GetProperty("y").GetInt32();
        }
    
        public static NotIndexList DeserializeNotIndexList(JsonElement _buf)
        {
            return new test.NotIndexList(_buf);
        }

        public int X { private set; get; }
        public int Y { private set; get; }

        private const int __ID__ = -50446599;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef(TablesComponent tables)
        {
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "x:" + X + ","
            + "y:" + Y + ","
            + "}";
        }

        partial void PostInit();
    }
}
