
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Text.Json;
using GameFrameX.Core.Config;

namespace GameFrameX.Config.test
{
    /// <summary>
    /// 圆
    /// </summary>
    public sealed partial class Circle : Shape
    {
        /*
        public Circle(float Radius)  : base() 
        {
            this.Radius = Radius;
            PostInit();
        }        
        */

        public Circle(JsonElement _buf)  : base(_buf) 
        {
            Radius = _buf.GetProperty("radius").GetSingle();
        }
    
        public static Circle DeserializeCircle(JsonElement _buf)
        {
            return new test.Circle(_buf);
        }

        /// <summary>
        /// 半径
        /// </summary>
        public float Radius { private set; get; }

        private const int __ID__ = 2131829196;
        public override int GetTypeId() => __ID__;

        public override void ResolveRef(TablesComponent tables)
        {
            base.ResolveRef(tables);
            
        }

        public override string ToString()
        {
            return "{ "
            + "radius:" + Radius + ","
            + "}";
        }

        partial void PostInit();
    }
}
