
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Text.Json;
using GameFrameX.Config.Core;

namespace GameFrameX.Config.test
{
    public sealed partial class TestScriptableObject : BeanBase
    {
        /*
        public TestScriptableObject(int Id, string Desc, float Rate, int Num, System.Numerics.Vector2 V2, System.Numerics.Vector3 V3, System.Numerics.Vector4 V4) 
        {
            this.Id = Id;
            this.Desc = Desc;
            this.Rate = Rate;
            this.Num = Num;
            this.V2 = V2;
            this.V3 = V3;
            this.V4 = V4;
            PostInit();
        }        
        */

        public TestScriptableObject(JsonElement _buf) 
        {
            Id = _buf.GetProperty("id").GetInt32();
            Desc = _buf.GetProperty("desc").GetString();
            Rate = _buf.GetProperty("rate").GetSingle();
            Num = _buf.GetProperty("num").GetInt32();
            V2 = ExternalTypeUtil.NewVector2(vec2.Deserializevec2(_buf.GetProperty("v2")));
            V3 = ExternalTypeUtil.NewVector3(vec3.Deserializevec3(_buf.GetProperty("v3")));
            V4 = ExternalTypeUtil.NewVector4(vec4.Deserializevec4(_buf.GetProperty("v4")));
        }
    
        public static TestScriptableObject DeserializeTestScriptableObject(JsonElement _buf)
        {
            return new test.TestScriptableObject(_buf);
        }

        public int Id { private set; get; }
        public string Desc { private set; get; }
        public float Rate { private set; get; }
        public int Num { private set; get; }
        public System.Numerics.Vector2 V2 { private set; get; }
        public System.Numerics.Vector3 V3 { private set; get; }
        public System.Numerics.Vector4 V4 { private set; get; }

        private const int __ID__ = -1896814350;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef(TablesComponent tables)
        {
            
            
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "id:" + Id + ","
            + "desc:" + Desc + ","
            + "rate:" + Rate + ","
            + "num:" + Num + ","
            + "v2:" + V2 + ","
            + "v3:" + V3 + ","
            + "v4:" + V4 + ","
            + "}";
        }

        partial void PostInit();
    }
}
