
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Text.Json;
using GameFrameX.Config.Core;

namespace GameFrameX.Config.test
{
    public sealed partial class DetectEncoding : BeanBase
    {
        /*
        public DetectEncoding(int Id, string Name) 
        {
            this.Id = Id;
            this.Name = Name;
            PostInit();
        }        
        */

        public DetectEncoding(JsonElement _buf) 
        {
            Id = _buf.GetProperty("id").GetInt32();
            Name = _buf.GetProperty("name").GetString();
        }
    
        public static DetectEncoding DeserializeDetectEncoding(JsonElement _buf)
        {
            return new test.DetectEncoding(_buf);
        }

        public int Id { private set; get; }
        public string Name { private set; get; }

        private const int __ID__ = -1154609646;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef(TablesComponent tables)
        {
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "id:" + Id + ","
            + "name:" + Name + ","
            + "}";
        }

        partial void PostInit();
    }
}
