
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Text.Json;
using GameFrameX.Core.Config;

namespace GameFrameX.Config.test
{
    public partial class TbDataFromMisc : BaseDataTable<test.DemoType2>
    {
        //private readonly System.Collections.Generic.Dictionary<int, test.DemoType2> _dataMap;
        //private readonly System.Collections.Generic.List<test.DemoType2> _dataList;
    
        //public System.Collections.Generic.Dictionary<int, test.DemoType2> DataMap => _dataMap;
        //public System.Collections.Generic.List<test.DemoType2> DataList => _dataList;
        //public test.DemoType2 GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
        //public test.DemoType2 Get(int key) => _dataMap[key];
        //public test.DemoType2 this[int key] => _dataMap[key];
    
        public override async System.Threading.Tasks.Task LoadAsync()
        {
            var jsonElement = await _loadFunc();
            DataList.Clear();
            LongDataMaps.Clear();
            StringDataMaps.Clear();
            foreach(var element in jsonElement.EnumerateArray())
            {
                test.DemoType2 _v;
                _v = test.DemoType2.DeserializeDemoType2(element);
                DataList.Add(_v);
                LongDataMaps.Add(_v.X4, _v);
                StringDataMaps.Add(_v.X4.ToString(), _v);
            }
            PostInit();
        }

        public void ResolveRef(TablesComponent tables)
        {
            foreach(var element in DataList)
            {
                element.ResolveRef(tables);
            }
        }
    
    
        partial void PostInit();

        public TbDataFromMisc(Func<Task<JsonElement>> loadFunc) : base(loadFunc)
        {
        }
    }
}
