
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Text.Json;
using GameFrameX.Core.Config;

namespace GameFrameX.Config.test
{
    public sealed partial class Foo : BeanBase
    {
        /*
        public Foo(int Y1, int Y2, int Y3) 
        {
            this.Y1 = Y1;
            this.Y2 = Y2;
            this.Y3 = Y3;
            PostInit();
        }        
        */

        public Foo(JsonElement _buf) 
        {
            Y1 = _buf.GetProperty("y1").GetInt32();
            Y2 = _buf.GetProperty("y2").GetInt32();
            Y3 = _buf.GetProperty("y3").GetInt32();
        }
    
        public static Foo DeserializeFoo(JsonElement _buf)
        {
            return new test.Foo(_buf);
        }

        public int Y1 { private set; get; }
        public int Y2 { private set; get; }
        public int Y3 { private set; get; }

        private const int __ID__ = -1147950774;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef(TablesComponent tables)
        {
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "y1:" + Y1 + ","
            + "y2:" + Y2 + ","
            + "y3:" + Y3 + ","
            + "}";
        }

        partial void PostInit();
    }
}
