
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Text.Json;
using GameFrameX.Config.Core;

namespace GameFrameX.Config.test
{
    public sealed partial class TestGlobal : BeanBase
    {
        /*
        public TestGlobal(int UnlockEquip, int UnlockHero) 
        {
            this.UnlockEquip = UnlockEquip;
            this.UnlockHero = UnlockHero;
            PostInit();
        }        
        */

        public TestGlobal(JsonElement _buf) 
        {
            UnlockEquip = _buf.GetProperty("unlock_equip").GetInt32();
            UnlockHero = _buf.GetProperty("unlock_hero").GetInt32();
        }
    
        public static TestGlobal DeserializeTestGlobal(JsonElement _buf)
        {
            return new test.TestGlobal(_buf);
        }

        public int UnlockEquip { private set; get; }
        public int UnlockHero { private set; get; }

        private const int __ID__ = -12548655;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef(TablesComponent tables)
        {
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "unlockEquip:" + UnlockEquip + ","
            + "unlockHero:" + UnlockHero + ","
            + "}";
        }

        partial void PostInit();
    }
}
