
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Text.Json;
using GameFrameX.Core.Config;

namespace GameFrameX.Config.test
{
    public abstract partial class ItemBase : BeanBase
    {
        /*
        public ItemBase(int Id, string Name, string Desc) 
        {
            this.Id = Id;
            this.Name = Name;
            this.Desc = Desc;
            PostInit();
        }        
        */

        public ItemBase(JsonElement _buf) 
        {
            Id = _buf.GetProperty("id").GetInt32();
            Name = _buf.GetProperty("name").GetString();
            Desc = _buf.GetProperty("desc").GetString();
        }
    
        public static ItemBase DeserializeItemBase(JsonElement _buf)
        {
            switch (_buf.GetProperty("$type").GetString())
            {
                case "Item": return new test.Item(_buf);
                case "Equipment": return new test.Equipment(_buf);
                case "Decorator": return new test.Decorator(_buf);
                default: throw new SerializationException();
            }
        }

        public int Id { private set; get; }
        public string Name { private set; get; }
        public string Desc { private set; get; }


        public virtual void ResolveRef(TablesComponent tables)
        {
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "id:" + Id + ","
            + "name:" + Name + ","
            + "desc:" + Desc + ","
            + "}";
        }

        partial void PostInit();
    }
}
