
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Text.Json;
using GameFrameX.Config.Core;

namespace GameFrameX.Config.test
{
    public partial class TbTestScriptableObject : BaseDataTable<test.TestScriptableObject>
    {
        //private readonly System.Collections.Generic.Dictionary<int, test.TestScriptableObject> _dataMap;
        //private readonly System.Collections.Generic.List<test.TestScriptableObject> _dataList;
    
        //public System.Collections.Generic.Dictionary<int, test.TestScriptableObject> DataMap => _dataMap;
        //public System.Collections.Generic.List<test.TestScriptableObject> DataList => _dataList;
        //public test.TestScriptableObject GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
        //public test.TestScriptableObject Get(int key) => _dataMap[key];
        //public test.TestScriptableObject this[int key] => _dataMap[key];
    
        public override async System.Threading.Tasks.Task LoadAsync()
        {
            var jsonElement = await _loadFunc();
            DataList.Clear();
            LongDataMaps.Clear();
            StringDataMaps.Clear();
            foreach(var element in jsonElement.EnumerateArray())
            {
                test.TestScriptableObject _v;
                _v = test.TestScriptableObject.DeserializeTestScriptableObject(element);
                DataList.Add(_v);
                LongDataMaps.Add(_v.Id, _v);
                StringDataMaps.Add(_v.Id.ToString(), _v);
            }
            PostInit();
        }

        public void ResolveRef(TablesComponent tables)
        {
            foreach(var element in DataList)
            {
                element.ResolveRef(tables);
            }
        }
    
    
        partial void PostInit();

        public TbTestScriptableObject(Func<Task<JsonElement>> loadFunc) : base(loadFunc)
        {
        }
    }
}
