
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Text.Json;
using GameFrameX.Core.Config;

namespace GameFrameX.Config.test
{
    public sealed partial class H2 : BeanBase
    {
        /*
        public H2(int Z2, int Z3) 
        {
            this.Z2 = Z2;
            this.Z3 = Z3;
            PostInit();
        }        
        */

        public H2(JsonElement _buf) 
        {
            Z2 = _buf.GetProperty("z2").GetInt32();
            Z3 = _buf.GetProperty("z3").GetInt32();
        }
    
        public static H2 DeserializeH2(JsonElement _buf)
        {
            return new test.H2(_buf);
        }

        public int Z2 { private set; get; }
        public int Z3 { private set; get; }

        private const int __ID__ = -1422503994;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef(TablesComponent tables)
        {
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "z2:" + Z2 + ","
            + "z3:" + Z3 + ","
            + "}";
        }

        partial void PostInit();
    }
}
