
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Text.Json;
using GameFrameX.Core.Config;

namespace GameFrameX.Config.test
{
    public sealed partial class TestSet : BeanBase
    {
        /*
        public TestSet(int Id, string X0, System.Collections.Generic.List<int> X1, System.Collections.Generic.List<long> X2, System.Collections.Generic.List<string> X3, System.Collections.Generic.List<test.DemoEnum> X4) 
        {
            this.Id = Id;
            this.X0 = X0;
            this.X1 = X1;
            this.X2 = X2;
            this.X3 = X3;
            this.X4 = X4;
            PostInit();
        }        
        */

        public TestSet(JsonElement _buf) 
        {
            Id = _buf.GetProperty("id").GetInt32();
            X0 = _buf.GetProperty("x0").GetString();
            { var __json0 = _buf.GetProperty("x1"); X1 = new System.Collections.Generic.List<int>(__json0.GetArrayLength()); foreach(JsonElement __e0 in __json0.EnumerateArray()) { int __v0;  __v0 = __e0.GetInt32();  X1.Add(__v0); }   }
            { var __json0 = _buf.GetProperty("x2"); X2 = new System.Collections.Generic.List<long>(__json0.GetArrayLength()); foreach(JsonElement __e0 in __json0.EnumerateArray()) { long __v0;  __v0 = __e0.GetInt64();  X2.Add(__v0); }   }
            { var __json0 = _buf.GetProperty("x3"); X3 = new System.Collections.Generic.List<string>(__json0.GetArrayLength()); foreach(JsonElement __e0 in __json0.EnumerateArray()) { string __v0;  __v0 = __e0.GetString();  X3.Add(__v0); }   }
            { var __json0 = _buf.GetProperty("x4"); X4 = new System.Collections.Generic.List<test.DemoEnum>(__json0.GetArrayLength()); foreach(JsonElement __e0 in __json0.EnumerateArray()) { test.DemoEnum __v0;  __v0 = (test.DemoEnum)__e0.GetInt32();  X4.Add(__v0); }   }
        }
    
        public static TestSet DeserializeTestSet(JsonElement _buf)
        {
            return new test.TestSet(_buf);
        }

        public int Id { private set; get; }
        public string X0 { private set; get; }
        public System.Collections.Generic.List<int> X1 { private set; get; }
        public System.Collections.Generic.List<long> X2 { private set; get; }
        public System.Collections.Generic.List<string> X3 { private set; get; }
        public System.Collections.Generic.List<test.DemoEnum> X4 { private set; get; }

        private const int __ID__ = -543221516;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef(TablesComponent tables)
        {
            
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "id:" + Id + ","
            + "x0:" + X0 + ","
            + "x1:" + StringUtil.CollectionToString(X1) + ","
            + "x2:" + StringUtil.CollectionToString(X2) + ","
            + "x3:" + StringUtil.CollectionToString(X3) + ","
            + "x4:" + StringUtil.CollectionToString(X4) + ","
            + "}";
        }

        partial void PostInit();
    }
}
