
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Text.Json;
using GameFrameX.Core.Config;

namespace GameFrameX.Config.test
{
    public sealed partial class H1 : BeanBase
    {
        /*
        public H1(test.H2 Y2, int Y3) 
        {
            this.Y2 = Y2;
            this.Y3 = Y3;
            PostInit();
        }        
        */

        public H1(JsonElement _buf) 
        {
            Y2 = test.H2.DeserializeH2(_buf.GetProperty("y2"));
            Y3 = _buf.GetProperty("y3").GetInt32();
        }
    
        public static H1 DeserializeH1(JsonElement _buf)
        {
            return new test.H1(_buf);
        }

        public test.H2 Y2 { private set; get; }
        public int Y3 { private set; get; }

        private const int __ID__ = -1422503995;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef(TablesComponent tables)
        {
            Y2?.ResolveRef(tables);
            
        }

        public override string ToString()
        {
            return "{ "
            + "y2:" + Y2 + ","
            + "y3:" + Y3 + ","
            + "}";
        }

        partial void PostInit();
    }
}
