
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Text.Json;
using GameFrameX.Core.Config;

namespace GameFrameX.Config
{
    public sealed partial class TimerParams : BeanBase
    {
        /*
        public TimerParams(int Level, float Number) 
        {
            this.Level = Level;
            this.Number = Number;
            PostInit();
        }        
        */

        public TimerParams(JsonElement _buf) 
        {
            Level = _buf.GetProperty("level").GetInt32();
            Number = _buf.GetProperty("number").GetSingle();
        }
    
        public static TimerParams DeserializeTimerParams(JsonElement _buf)
        {
            return new TimerParams(_buf);
        }

        /// <summary>
        /// 难度级别
        /// </summary>
        public int Level { private set; get; }
        /// <summary>
        /// 天选值
        /// </summary>
        public float Number { private set; get; }

        private const int __ID__ = 1186614539;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef(TablesComponent tables)
        {
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "level:" + Level + ","
            + "number:" + Number + ","
            + "}";
        }

        partial void PostInit();
    }
}
