
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Text.Json;
using GameFrameX.Core.Config;

namespace GameFrameX.Config
{
    /// <summary>
    /// 用于保存中文原content以及对应的国际化Key
    /// </summary>
    public sealed partial class TranslateCKBean : BeanBase
    {
        /*
        public TranslateCKBean(string Content, string Key) 
        {
            this.Content = Content;
            this.Key = Key;
            PostInit();
        }        
        */

        public TranslateCKBean(JsonElement _buf) 
        {
            Content = _buf.GetProperty("content").GetString();
            Key = _buf.GetProperty("key").GetString();
        }
    
        public static TranslateCKBean DeserializeTranslateCKBean(JsonElement _buf)
        {
            return new TranslateCKBean(_buf);
        }

        /// <summary>
        /// 内容
        /// </summary>
        public string Content { private set; get; }
        /// <summary>
        /// 对应Key
        /// </summary>
        public string Key { private set; get; }

        private const int __ID__ = 1171657446;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef(TablesComponent tables)
        {
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "content:" + Content + ","
            + "key:" + Key + ","
            + "}";
        }

        partial void PostInit();
    }
}
