
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Text.Json;
using GameFrameX.Core.Config;

namespace GameFrameX.Config
{
    public partial struct vec2
    {

        private System.Func<string, string, string> Translator;

        /*
        public vec2(float X, float Y) 
        {
            this.X = X;
            this.Y = Y;
            PostInit();
        }        
        */

        public vec2(JsonElement _buf) 
        {
            Translator = null;
            X = _buf.GetProperty("x").GetSingle();
            Y = _buf.GetProperty("y").GetSingle();

            // Localization Key Begin
            // Localization Key End
        }
    
        public static vec2 Deserializevec2(JsonElement _buf)
        {
            return new vec2(_buf);
        }

        public float X { private set; get; }
        public float Y { private set; get; }


        public  void ResolveRef(TablesComponent tables)
        {
            
            
        }

        public  void TranslateText(System.Func<string, string, string> translator)
        {
            Translator = translator;
        }

        public override string ToString()
        {
            return "{ "
            + "x:" + X + ","
            + "y:" + Y + ","
            + "}";
        }

        partial void PostInit();
    }
}
