
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Text.Json;
using GameFrameX.Core.Config;

namespace GameFrameX.Config
{
    public sealed partial class VideoTextSubtitles : BeanBase
    {
        /*
        public VideoTextSubtitles(int Time, TranslateCKBean Content) 
        {
            this.Time = Time;
            this.Content = Content;
            PostInit();
        }        
        */

        public VideoTextSubtitles(JsonElement _buf) 
        {
            Time = _buf.GetProperty("Time").GetInt32();
            Content = TranslateCKBean.DeserializeTranslateCKBean(_buf.GetProperty("Content"));
        }
    
        public static VideoTextSubtitles DeserializeVideoTextSubtitles(JsonElement _buf)
        {
            return new VideoTextSubtitles(_buf);
        }

        /// <summary>
        /// 时间
        /// </summary>
        public int Time { private set; get; }
        /// <summary>
        /// 字幕内容
        /// </summary>
        public TranslateCKBean Content { private set; get; }

        private const int __ID__ = -14693357;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef(TablesComponent tables)
        {
            
            Content?.ResolveRef(tables);
        }

        public override string ToString()
        {
            return "{ "
            + "Time:" + Time + ","
            + "Content:" + Content + ","
            + "}";
        }

        partial void PostInit();
    }
}
