
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Text.Json;
using GameFrameX.Core.Config;

namespace GameFrameX.Config.item
{
    public partial class TbAchievement : BaseDataTable<item.Achievement>
    {
        //private readonly System.Collections.Generic.Dictionary<int, item.Achievement> _dataMap;
        //private readonly System.Collections.Generic.List<item.Achievement> _dataList;
    
        //public System.Collections.Generic.Dictionary<int, item.Achievement> DataMap => _dataMap;
        //public System.Collections.Generic.List<item.Achievement> DataList => _dataList;
        //public item.Achievement GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
        //public item.Achievement Get(int key) => _dataMap[key];
        //public item.Achievement this[int key] => _dataMap[key];
    
        public override async System.Threading.Tasks.Task LoadAsync()
        {
            var jsonElement = await _loadFunc();
            DataList.Clear();
            LongDataMaps.Clear();
            StringDataMaps.Clear();
            foreach(var element in jsonElement.EnumerateArray())
            {
                item.Achievement _v;
                _v = item.Achievement.DeserializeAchievement(element);
                DataList.Add(_v);
                LongDataMaps.Add(_v.Id, _v);
                StringDataMaps.Add(_v.Id.ToString(), _v);
            }
            PostInit();
        }

        public void ResolveRef(TablesComponent tables)
        {
            foreach(var element in DataList)
            {
                element.ResolveRef(tables);
            }
        }
    
    
        partial void PostInit();

        public TbAchievement(Func<Task<JsonElement>> loadFunc) : base(loadFunc)
        {
        }
    }
}
